# Generated by Django 5.2.5 on 2025-08-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_marca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosCadastradosTiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Lista_Produtos', models.CharField(max_length=30)),
                ('Lista_Produtos', models.JSONField(default=dict)),
            ],
        ),
    ]
