# Generated by Django 5.2.5 on 2025-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtoscadastradostiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoscadastradostiny',
            name='Data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
