# Generated by Django 5.2.5 on 2025-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produtoscadastradostiny_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosProcessados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workbook', models.FileField(upload_to='uploaded_files/')),
                ('fornecedor', models.CharField(max_length=50)),
                ('tipo_giro_compras', models.CharField(max_length=50)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='processed_outputs/')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Processando', 'Processando'), ('Completo', 'Completo'), ('Falha', 'Falha')], default='Pendente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo Processado',
                'verbose_name_plural': 'Arquivos Processados',
            },
        ),
    ]
