# Generated by Django 5.2.5 on 2025-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_arquivosprocessados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivosprocessados',
            old_name='fornecedor',
            new_name='Fornecedor',
        ),
        migrations.RenameField(
            model_name='arquivosprocessados',
            old_name='workbook',
            new_name='Workbook',
        ),
        migrations.RenameField(
            model_name='arquivosprocessados',
            old_name='tipo_giro_compras',
            new_name='situacao_compra',
        ),
    ]
