# Generated by Django 5.2.5 on 2025-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_fornecedor_arquivosprocessados_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosAtivosTiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tiny', models.CharField(max_length=9)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('situacao', models.CharField(max_length=50)),
                ('marketplace', models.CharField(max_length=50)),
                ('data_pedido', models.DateTimeField()),
                ('skus_vendidos', models.ManyToManyField(to='core.produtosativostiny')),
            ],
        ),
    ]
