# Generated by Django 5.2.5 on 2025-09-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produtosativostiny_pedidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtosativostiny',
            options={'verbose_name': 'Produto Ativo Tiny', 'verbose_name_plural': 'Produtos Ativo Tiny'},
        ),
    ]
