# Generated by Django 5.2.5 on 2025-09-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_produtosativostiny_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
