# Generated by Django 5.2.5 on 2025-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_tiny',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
