# Generated by Django 5.2.5 on 2025-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pedidos_id_tiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valores_unicos',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
