# Generated by Django 5.2.5 on 2025-09-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pedidos_valores_unicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='valores_unicos',
            new_name='valores',
        ),
    ]
