# Generated by Django 5.2.5 on 2025-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_valores_unicos_pedidos_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valores',
            field=models.JSONField(),
        ),
    ]
