# Generated by Django 5.2.5 on 2025-09-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pedidos_valores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='skus_vendidos',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='valores',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sku_vendido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.produtosativostiny'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_tiny',
            field=models.CharField(max_length=9),
        ),
    ]
