# Generated by Django 5.2.5 on 2025-09-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pedidos_skus_vendidos_remove_pedidos_valores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='sku_vendido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produtosativostiny'),
        ),
    ]
