# Generated by Django 5.2.5 on 2025-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pedidos_sku_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='marca',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
