# Generated by Django 5.2.5 on 2025-09-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedidos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca'),
        ),
    ]
