# Generated by Django 5.2.5 on 2025-09-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pedidos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosativostiny',
            name='ean',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
