# Generated by Django 5.2.5 on 2025-09-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_produtosativostiny_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosativostiny',
            name='ean',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
