# Generated by Django 5.2.5 on 2025-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_produtosativostiny_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUltimaAtualizacaoCustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataUltima', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='produtosativostiny',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
