# Generated by Django 5.2.5 on 2025-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dataultimaatualizacaocustos_produtosativostiny_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosativostiny',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
