# Generated by Django 5.2.5 on 2025-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_produtosativostiny_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
